# Generated by Django 5.1.3 on 2024-11-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naombre', models.CharField(max_length=60)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('imagen', models.ImageField(upload_to='uploads/products/')),
            ],
        ),
    ]
