# Generated by Django 4.2.16 on 2024-11-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEsoterica', '0002_perfil_codigo_postal_perfil_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='historial_compras',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='preferencias_esotericas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
