# Generated by Django 5.1.3 on 2024-11-21 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEsoterica', '0003_remove_perfil_historial_compras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('P', 'Pedido'), ('C', 'En camino'), ('E', 'Enviado')], default='P', max_length=1)),
                ('direccion_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_seguimiento', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_actualizacion_estado', models.DateTimeField(auto_now=True)),
                ('productos', models.ManyToManyField(related_name='pedidos', to='tiendaEsoterica.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
