# Generated by Django 5.1.3 on 2024-11-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEsoterica', '0002_carrito_carritoitem_carrito_productos'),
        ('tiendaEsoterica', '0004_pedido'),
    ]

    operations = [
    ]
