# Generated by Django 4.2.16 on 2024-11-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEsoterica', '0002_carrito_carritoitem_carrito_productos'),
        ('tiendaEsoterica', '0004_pedido'),
    ]

    operations = [
    ]
