# Generated by Django 5.1.3 on 2024-11-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEsoterica', '0005_merge_20241122_1642'),
        ('tiendaEsoterica', '0005_merge_20241122_1853'),
    ]

    operations = [
    ]
