# Generated by Django 5.1.2 on 2024-11-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEsoterica', '0006_merge_20241123_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('P', 'Pedido'), ('C', 'Enviado'), ('E', 'Entregado'), ('X', 'Cancelado')], default='P', max_length=1),
        ),
    ]
