# Generated by Django 5.1.3 on 2024-11-27 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEsoterica', '0008_remove_pedido_productos_pedidoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tiendaEsoterica.pedido'),
        ),
    ]
