# Generated by Django 5.1.3 on 2024-11-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEsoterica', '0009_alter_pedidoitem_cantidad_alter_pedidoitem_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('contrareembolso', 'Contrareembolso'), ('pasarela', 'Pasarela de Pago')], default='pasarela', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Enviado'), ('E', 'Entregado'), ('X', 'Cancelado')], default='P', max_length=1),
        ),
    ]
