# Generated by Django 5.1.3 on 2024-12-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEsoterica', '0008_producto_cantidad'),
        ('tiendaEsoterica', '0012_pedido_email'),
    ]

    operations = [
    ]
